module.exports = [
    {
        id: 1,
        title: `Quote Generator`,
        slug: `quote-generator`,
        imgUrl: `https://images.unsplash.com/photo-1457369804613-52c61a468e7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80`,
        url: `Url`,
        featured: false,
        description: `A generator of inspirational quotes that I've collected along the way.`,
        technologiesUsed: `React`,
    },
    {
        id: 2,
        title: `GigHub`,
        slug: `gighub`,
        imgUrl: `https://brittanyellichpublic.s3-us-west-2.amazonaws.com/gighubimage.PNG`,
        url: `https://github.com/b-marie/GigHub`,
        featured: false,
        description: `Social media project to share upcoming concerts.`,
        technologiesUsed: `C#, .NET, Entity Framework`,
    },
    {
        id: 3,
        title: `TimeTidy`,
        slug: `timetidy`,
        imgUrl: `https://brittanyellichpublic.s3-us-west-2.amazonaws.com/timetidyimage.PNG`,
        url: `https://github.com/b-marie/TimeTidy2`,
        featured: false,
        description: `Application with a calendar, appointment, and customer information tracking system.`,
        technologiesUsed: `Java, JavaFx`,
    },
    {
        id: 4,
        title: `Inventory Management System`,
        slug: `inventory-management-system`,
        imgUrl: `https://brittanyellichpublic.s3-us-west-2.amazonaws.com/inventorymanagementsystemimage.PNG`,
        url: `https://github.com/b-marie/InventoryManagementSystem`,
        featured: false,
        description: `Project to add, store, and track parts and products in an inventory management system.`,
        technologiesUsed: `Java, JavaFx`,
    },
    {
        id: 5,
        title: `The RGB Color Game`,
        slug: `rgb-color-game`,
        imgUrl: `https://brittanyellichpublic.s3-us-west-2.amazonaws.com/rgbcolorgameimage.PNG`,
        url: `https://beemarie.org/portfolio/colorGame.html`,
        featured: false,
        description: `A game to help you become more familiar with RGB colors`,
        technologiesUsed: `Javascript, HTML, CSS`,
    },
]